import classes
#Armour======================================================================
ha0001 = classes.heavyArmour(ID = 'ha0001',
                             name = 'Iron Armor',
                             weight = 10,
                             value = 100,
                             desc = 'A simple set of iron armor',
                             apparelClass = 'heavy',
                             defense = 10,
                             effects = 'none')
la0001 = classes.lightArmour(ID = 'la0001',
                             name = 'Leather Armor',
                             weight = 5,
                             value = 100,
                             desc = 'A simple set of leather armor',
                             apparelClass = 'light',
                             defense = 5,
                             effects = 'none')
cl0001 = classes.clothing(ID = 'cl0001',
                          name = 'Apprentice Robes',
                             weight = 1,
                             value = 100,
                             desc = 'A simple set of robes',
                             apparelClass = 'clothing',
                             defense = 0,
                             effects = 'none')
#Weapons======================================================================
hw0001 = classes.heavyWeapon(ID = 'hw0001',
                             name = 'Iron Sword',
                             weight = 10,
                             value = 100,
                             desc = 'A simple iron sword',
                             weaponClass = 'heavy',
                             effects = 'none',
                             move1 = 'slash',
                             move2 = 'stab',
                             move3 = 'bash',
                             StrReq = 10,
                             DexReq = 4,
                             IntReq = 0)
lw0001 = classes.lightWeapon(ID = 'lw0001',
                             name = 'Iron Dagger',
                             weight = 2,
                             value = 100,
                             desc = 'A simple iron dagger',
                             weaponClass = 'light',
                             effects = 'none',
                             move1 = 'slash',
                             move2 = 'stab',
                             move3 = 'evade',
                             StrReq = 4,
                             DexReq = 10,
                             IntReq = 0)
mw0001 = classes.magicWeapon(ID = 'mw0001',
                             name = 'wood staff',
                             weight = 7,
                             value = 100,
                             desc = 'A simple sorcerer staff',
                             weaponClass = 'magic',
                             effects = 'none',
                             move1 = 'fireball',
                             move2 = 'frostfall',
                             move3 = 'magicshield',
                             StrReq = 10,
                             DexReq = 4,
                             IntReq = 0)
#Accessories==================================================================
Ac0001 = classes.
